Vagrant.configure(2) do |config|

  config.vm.box = "dharmab/centos7"

  config.vm.synced_folder "../src/redlabel/express/", "/express"

  config.vm.provision "ansible" do |ansible|
    ansible.limit = "all"
    ansible.playbook = "../playbooks/site.yml"
    ansible.sudo = true
    ansible.sudo_user = "root"
    ansible.inventory_path = "inventory"
  end
  config.vm.provision "ansible", run: "always" do |ansible|
    ansible.limit = "all"
    ansible.sudo = true
    ansible.sudo_user = "root"
    ansible.inventory_path = "inventory"
    ansible.playbook = "../playbooks/site.yml"
  end

end
