---
- name: Add repo file
  template: src=nginx_centos.repo.j2 dest=/etc/yum.repos.d/nginx.repo owner=root group=root mode=0644

- name: Add repo key
  get_url: url=http://nginx.org/keys/nginx_signing.key dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-nginx sha256sum=

- name: Add repo key
  file: path=/etc/pki/rpm-gpg/RPM-GPG-KEY-nginx owner=root group=root mode=0644

- name: Add repo key
  rpm_key: state=present key=/etc/pki/rpm-gpg/RPM-GPG-KEY-nginx

- name: Install Nginx
  yum: name=nginx enablerepo=nginx state=present

# - name: remove default.conf
#   file: path=/etc/nginx/conf.d/default.conf state=absent
#
# - name: copy custom nginx.conf
#   copy: src=../../../conf/redlabel/nginx/nginx.conf dest=/etc/nginx/nginx.conf
#
# - name: link vhost.conf.d
#   file: src=../../../conf/redlabel/nginx/nginx dest=/etc/nginx/vhost.conf.d state=link
