---
- include_vars: centos.yml

- name: Install Supervisord
  yum: name={{ supervisor_package }} enablerepo=epel state=present

- name: Start and enable service
  service: name={{ supervisor_service }} state=started enabled=yes
